# Java 21 LTS is rock solid and guaranteed to exist
FROM maven:3.9-eclipse-temurin-25-alpine

LABEL maintainer="Khova Krishna Pilato" \ description="Development Docker image for Spring Boot app"

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

EXPOSE 8080
ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"

ENTRYPOINT ["sh", "-c", "mvn spring-boot:run -Dspring-boot.run.jvmArguments='${JAVA_OPTS}'"]