name: Deploy Frontend

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    
    # This ensures all 'run' commands start inside the react-app folder
    defaults:
      run:
        working-directory: ./frontend/react-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Dependencies
        # Using 'npm ci' is faster and more reliable for CI/CD than 'npm install'
        run: npm ci

      - name: Build React App
        # Building the project with the base path for GitHub Pages
        run: npm run build -- --base=/portfolio/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Path relative to the repository root
          publish_dir: ./frontend/react-app/dist
