name: Deploy Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend/react-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build React App
        run: npm run build -- --base=/portfolio/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/react-app/dist
